export const styleNameMap: Record<string, string> = {
  colorful: "Rangdor",
  kids: "Bolalar",
  "floral-frame": "Gullar ramkasi",
  butterfly: "Kapalak",
  "kids-photo": "Bolalar surati",
  unicorn: "Yakkashox",
  "floral-gold": "Oltin gullar",
  "elegant-frame": "Elegant ramka",
  "blue-floral": "Ko'k gullar",
  "golden-ornament": "Oltin bezak",
  "floral-hexagon": "Oltiburchak gullar",
  romantic: "Romantik",
  national: "Milliy",
  "floral-engagement": "Gullar bilan bezatilgan",
  "modern-engagement": "Zamonaviy",
  "traditional-engagement": "An'anaviy",
  traditional: "An'anaviy",
  calm: "Sokin",
  "photo-memorial": "Surat bilan",
  "elegant-memorial": "Elegant",
  "islamic-memorial": "Islomiy",
};
